token: <BOT_TOKEN>
services:
    - service: <SERVICE_NAME>
      user: true
      # Journalctl "--output" flag
      # Allowed:
      #  | "short"
      #  | "short-full"
      #  | "short-iso"
      #  | "short-iso-precise"
      #  | "short-precise"
      #  | "short-monotonic"
      #  | "short-delta"
      #  | "short-unix"
      #  | "verbose"
      #  | "export"
      #  | "json"
      #  | "json-pretty"
      #  | "json-sse"
      #  | "json-seq"
      #  | "cat"
      #  | "with-unit"
      output: cat
      # Journalctl "--since" flag
      # Allowed: DATUM("YYYY-MM-DD HH:MM:SS") | "today" | "yesterday"
      since: yesterday
    - service: ssh
      user: false
      output: short
      since: yesterday
