# NOTE: This is just an example
define:
  - &PGPressServerChatID <number>

# `[]tgs.Scope`
scopes:
  - type: chat
    chat_id: *PGPressServerChatID

# `tgs.Targets`
targets:
  chats:
    - id: *PGPressServerChatID
      type: supergroup
      message_thread_id: <number>
