# NOTE: This is just an example
define:
    - &AliceChatID <number>

# `[]tgs.Scope`
scopes:
    - type: chat
      chat_id: *AliceChatID

# `tgs.Targets`
targets:
    chats:
        # Types: "private", "group", "supergroup" or "channel"
        - type: supergroup
          id: *AliceChatID
          message_thread_id: 5
