# NOTE: This is just an example
define:
    - &AliceChatID <number>

# `[]tgs.Scope`
scopes:
    - type: chat
      chat_id: *AliceChatID

# `tgs.Targets`
targets:
    chats:
        - id: *AliceChatID
          type: supergroup
          message_thread_id: 3

units:
    system:
        - name: ssh
          output: short
    user:
        - name: picow-led
          output: cat
        - name: op-anime-dl
          output: cat
        - name: op-manga-dl
          output: cat
        - name: tgs-server
          output: cat
        - name: test-oauth
          output: cat
        - name: pg-vis-pwa
          output: cat
        - name: shift-scheduler
          output: cat
