# NOTE: This is just an example
define:
    - &OPChatID <number>

register:
    - type: chat
      chat_id: *OPChatID

targets:
    chats:
        - id: *OPChatID
          type: supergroup
          message_thread_id: 3
        - id: *OPChatID
          type: supergroup
          message_thread_id: 175

path: "/mnt/media/Data/One Piece/Manga"
