# NOTE: This is just an example
define:
    - &PGVisServerChatID <number>

# `[]tgs.Scope`
scopes:
    - type: chat
      chat_id: *PGVisServerChatID

# `tgs.Targets`
targets:
    chats:
        - id: *PGVisServerChatID
          type: supergroup
          message_thread_id: <number>
