# NOTE: This is just an example
define:
    - &PGVisServerChatID <number>

register:
    - type: chat
      chat_id: *PGVisServerChatID

targets:
    chats:
        - id: *PGVisServerChatID
          type: supergroup
          message_thread_id: <number>
