define:
    - &AliceChatID <number>
    - &OPChatID <number>

token: <token>

stats:
    register:
        - type: default
        - type: chat
          chat_id: *AliceChatID

    targets:
        all: true

opmanga:
    register:
        - type: chat
          chat_id: *OPChatID

    targets:
        chats:
            - id: *OPChatID
              type: supergroup
              message_thread_id: 2
            - id: *OPChatID
              type: supergroup
              message_thread_id: 3

    path: "/Volumes/media/Data/One Piece/Manga"
