define:
    - &AliceChatID <number>
    - &OPChatID <number>

token: <token>

stats:
    register:
        - type: default
        - type: chat
          chat_id: *AliceChatID

    targets:
        all: true

journal:
    register:
        - type: chat
          chat_id: *AliceChatID

    targets:
        chats:
            - id: *AliceChatID
              type: supergroup
              message_thread_id: 3

    units:
        system:
            - name: ssh
              output: short
        user:
            - name: picow-led-server
              output: cat
            - name: op-anime-dl
              output: cat
            - name: op-manga-dl
              output: cat
            - name: tgs-server
              output: cat

opmanga:
    register:
        - type: chat
          chat_id: *OPChatID

    targets:
        chats:
            - id: *OPChatID
              type: supergroup
              message_thread_id: 2
            - id: *OPChatID
              type: supergroup
              message_thread_id: 3

    path: "/Volumes/media/Data/One Piece/Manga"
