define:
    - &AliceChatID <number>
    - &OPChatID <number>

token: <token>

ip:
    # `[]tgbotapi.BotCommandScope`
    register:
        # Types:
        #   - default
        #   - all_private_chats
        #   - all_group_chats
        #   - all_chat_administrators
        #   - chat, needs: "chat_id"
        #   - chat_administrators, needs: "chat_id"
        #   - chat_member, needs: "chat_id" & "user_id"
        - type: chat
          chat_id: *AliceChatID

    targets:
        # Currently,you can only set either chat IDs or user IDs, not both. Combining these options
        # is not possible (yet)
        chats:
            - id: *AliceChatID
              # Type of chat, can be either "private", "group", "supergroup" or "channel"
              type: supergroup
              message_thread_id: 5

stats:
    register:
        - type: default
        - type: chat
          chat_id: *AliceChatID

    targets:
        all: true

journal:
    register:
        - type: chat
          chat_id: *AliceChatID

    targets:
        chats:
            - id: *AliceChatID
              type: supergroup
              message_thread_id: 3

    units:
        system:
            - name: ssh
              output: short
        user:
            - name: picow-led-server
              output: cat
            - name: op-anime-dl
              output: cat
            - name: op-manga-dl
              output: cat
            - name: tgs-server
              output: cat

opmanga:
    register:
        - type: chat
          chat_id: *OPChatID

    targets:
        chats:
            - id: *OPChatID
              type: supergroup
              message_thread_id: 2
            - id: *OPChatID
              type: supergroup
              message_thread_id: 3

    path: "/Volumes/media/Data/One Piece/Manga"
