define:
    - &UserID <number>
    - &ChatID -<number>

token: <token>

ip:
    register:
        - id: *ChatID
          type: chat

    targets:
        chats:
            - id: *ChatID
              # Type of chat, can be either "private", "group", "supergroup" or "channel"
              type: supergroup
