token: <BOT_TOKEN>

# Global targets, Used as fallback for commands
targets:
    users:
        - id: <USER_ID>
    chats:
        - id: <CHAT_ID>

commands:
    ip:
        targets:
            users:
                - <USER_ID>
            chats:
                - <CHAT_ID>

    journallist:

    journal:

    picowstatus:

    picowon:

    picowoff:

    opmanga:

    opmangalist:
