token: <BOT_TOKEN>

targets:
    - <USER_ID/CHAT_ID>

commands:
    ip:
        targets:
            - <USER_ID/CHAT_ID>

    journallist:
        #targets:

    journal:
        targets:
            - <USER_ID/CHAT_ID>

    picowstatus:
        targets:
            - <USER_ID/CHAT_ID>

    picowon:
        targets:
            - <USER_ID/CHAT_ID>

    picowoff:
        targets:
            - <USER_ID/CHAT_ID>

    opmanga:
        #targets:

    opmangalist:
        #targets:
