define:
    - &UserID <number>
    - &ChatID -<number>

token: <token>

ip:
    # `[]tgbotapi.BotCommandScope`
    register:
        # Types:
        #   - default
        #   - all_private_chats
        #   - all_group_chats
        #   - all_chat_administrators
        #   - chat
        #   - chat_administrators
        #   - chat_member
        - type: chat
          chat_id: *ChatID
          #user_id: *UserID

    targets:
        # If set to true, all users in every chat are allowed to run this command
        all: false

        users:
            - id: *UserID
        chats:
            - id: *ChatID
              # Types:
              #     - private
              #     - group
              #     - supergroup
              #     - channel
              type: supergroup
              message_thread_id: <number>
